---
- name: Check if PostgreSQL repo is installed
  ansible.builtin.stat:
    path: /etc/yum.repos.d/pgdg-redhat-all.repo
  register: postgresql_repo_file
  tags:
    - postgresql

- name: Install PostgreSQL repo RPM
  ansible.builtin.dnf:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
    disable_gpg_check: true
  when: not postgresql_repo_file.stat.exists
  tags:
    - postgresql

- name: Disable built-in PostgreSQL module
  ansible.builtin.command: dnf -qy module disable postgresql
  register: postgresql_module_disable
  changed_when: "'Nothing to do' not in postgresql_module_disable.stdout"
  failed_when: false
  tags:
    - postgresql
