---

### By default, certificate generation uses detailed organization info (parameter 'ORG').
### To generate certificates with only 'COMMON NAME', set the variable
### 'easyrsa.pki.easyrsa_dn' to 'cn'.

# easyrsa:
#   pki:
#     - name: 'pki1'         				  # NO default
#       easyrsa_dn: 'cn_only'         # default: 'org'
#       ca_expire: 1825               # default: 3650
#       cert_expire: 365              # default: 730
#
#       cacerts:
#         cn: 'Barok CA'              # NO default
#         email: 'name@domain.tld'    # default: ''
#         org_name: 'Firma'           # default: 'Firma'
#         password: 'secret'          # default: ''
#         country: 'SK'               # default: 'CZ'
#         state: 'Slovensko'          # default: 'Ceska Rebuplika'
#         city: 'Prague'              # default: 'Hradec Kralove'
#         org_unit: 'Obchod'          # default: 'IT'
#
#       servercerts:
#         - cn: domain.tld            # NO default
#           country: 'SK'             # default: 'CZ'
#           state: 'Kanada'    		    # default: 'Ceska Republika'
#           city: 'Toronto'       		# default: 'Hradec Kralove'
#           org_name: 'Barok'        	# default: 'Firma'
#           email: 'name@mail.tld'    # default: ''
#           org_unit: 'Obchod'     		# default: 'IT'
#
#       clientcerts:
#         - cn: username              # NO default
#           password: 'secret'        # NO default
#           country: 'SK'             # default: 'CZ'
#           state: 'Kanada'    		    # default: 'Ceska Republika'
#           city: 'Toronto'       		# default: 'Hradec Kralove'
#           org_name: 'Barok'        	# default: 'Firma'
#           email: 'name@mail.tld'    # default: ''
#           org_unit: 'Obchod'     		# default: 'IT'
#         
#
### Minimal example (usually sufficient):
# easyrsa:
#   pki:
#     - name: 'pkiname'
#
#       cacerts:
#         password: 'secret'
#         org_name: 'Firma, s.r.o.' 
#         cn: 'Firma CA'
#         email: 'name@domain.tld'
#
#       servercerts:
#         - cn: domain.tld
#           org_name: 'Firma, s.r.o.'
#           email: 'name@domain.tld'
#       
#       clientcerts:
#         - cn: username
#           password: 'secret'
#           org_name: 'Firma, s.r.o.'
#           email: 'username@domain.tld'

easyrsa_installdir: '/srv/easy-rsa'

### CA CERTIFICATE DEFAULTS ###
easyrsa_ca_country_name_default: 'CZ'
easyrsa_ca_state_default: 'Ceska Republika'
easyrsa_ca_city_default: 'Hradec Kralove'
easyrsa_ca_org_name_default: 'Firma'
easyrsa_ca_email_default: ''
easyrsa_ca_org_unit_default: 'IT'
### END ###

### SERVER CERTIFICATE DEFAULTS ###
easyrsa_server_country_name_default: 'CZ'
easyrsa_server_state_default: 'Ceska Republika'
easyrsa_server_city_default: 'Hradec Kralove'
easyrsa_server_org_name_default: 'Firma'
easyrsa_server_email_default: ''
easyrsa_server_org_unit_default: 'IT'
### END ###

### CLIENT CERTIFICATE DEFAULTS ###
easyrsa_client_country_name_default: 'CZ'
easyrsa_client_state_default: 'Ceska Republika'
easyrsa_client_city_default: 'Hradec Kralove'
easyrsa_client_org_name_default: 'Firma'
easyrsa_client_email_default: ''
easyrsa_client_org_unit_default: 'IT'
### END ###
 
