---
galaxy_info:
  author: stepankutaj
  description: Redis cache and message broker
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - database
    - cache
    - redis
dependencies: []
