---
- name: Include os-specific vars
  include: 'vars.yml'
  tags:
    - htpasswd_config

- name: Include distribution installation
  include: "{{ item }}"
  with_first_found:
  - files:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    skip: true

- name: 'Install htpasswd packages for Linux OS'
  package: name={{ item }} state=installed
  with_items:
    - "{{ htpasswd_packages }}"
  when: ansible_os_family != "FreeBSD"

- name: Install dependencies package for bcrypt
  pip: name=bcrypt state=present
  when: ansible_os_family != "FreeBSD"

- name: Creating htpasswd folder
  file: dest={{ htpasswd_path_dir }} state=directory owner=root group={{ htpasswd_system_root_group }} mode=0755

- name: Adding htpasswd files
  htpasswd:
    name: "{{ item.1.name }}"
    path: "{{ item.0.path | default(htpasswd_path_dir) ~ '/' ~ item.0.name }}"
    crypt_scheme: "{{ item.0.crypt | default(htpasswd_crypt) }}"
    owner: "{{ item.0.owner | default(htpasswd_owner) }}"
    group: "{{ item.0.group | default(htpasswd_system_root_group) }}"
    mode: "{{ item.0.mode | default(htpasswd_mode) }}"
    password: "{{ item.1.password }}"
  with_subelements:
    - '{{ htpasswd }}'
    - users
