---

- name: 'Set hostname'
  hostname: name="{{ hostname | default(inventory_hostname) }}"
  when: ansible_virtualization_type != "openvz" and ansible_virtualization_type != "lxc"

- name: 'Check if NetworkManager.conf is exist'
  stat: path=/etc/NetworkManager/NetworkManager.conf
  register: networkmanager_conf_file

- name: 'Disable set resolv.conf by NetworkManager'
  lineinfile: path=/etc/NetworkManager/NetworkManager.conf  regexp='^dns=none' insertafter='^\[main\]' line='dns=none'
  when: networkmanager_conf_file.stat.exists

- name: 'Edit /etc/hosts'
  lineinfile: dest=/etc/hosts regexp="^{{ item.key }} " line="{{ item.key }}  {{ item.value }}"
  with_dict: "{{ hosts }}"
  when: hosts is defined
  tags:
    - hosts