---

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
  tags:
    - upgrade

- name: Upgrade all Homebrew packages
  community.general.homebrew:
    upgrade_all: true
  register: upgrade_brew_result
  tags:
    - upgrade

- name: Clean Homebrew cache
  ansible.builtin.command: brew cleanup
  when: upgrade_clean_cache | bool
  changed_when: false
  tags:
    - upgrade
