---

- name: Update Homebrew
  homebrew:
    update_homebrew: true
  tags:
    - upgrade

- name: Upgrade all Homebrew packages
  homebrew:
    upgrade_all: true
  register: brew_upgrade
  tags:
    - upgrade

- name: Clean Homebrew cache
  command: brew cleanup
  when: upgrade_clean_cache | bool
  changed_when: false
  tags:
    - upgrade
