---

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags:
    - upgrade

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: "{{ 'dist' if upgrade_dist_upgrade else 'safe' }}"
  register: upgrade_apt_result
  tags:
    - upgrade

- name: Remove unused packages
  ansible.builtin.apt:
    autoremove: true
    purge: true
  when: upgrade_autoremove | bool
  tags:
    - upgrade

- name: Clean apt cache
  ansible.builtin.apt:
    autoclean: true
  when: upgrade_clean_cache | bool
  tags:
    - upgrade
