---

- name: Update package repository
  ansible.builtin.command: pkg update -f
  changed_when: false
  tags:
    - upgrade

- name: Upgrade all packages
  ansible.builtin.command: pkg upgrade -y
  register: upgrade_pkg_result
  changed_when: "'Nothing to do' not in upgrade_pkg_result.stdout"
  tags:
    - upgrade

- name: Clean package cache
  ansible.builtin.command: pkg clean -ay
  when: upgrade_clean_cache | bool
  changed_when: false
  tags:
    - upgrade

- name: Remove unused packages
  ansible.builtin.command: pkg autoremove -y
  when: upgrade_autoremove | bool
  register: upgrade_pkg_autoremove
  changed_when: "'Nothing to do' not in upgrade_pkg_autoremove.stdout"
  tags:
    - upgrade
