---

- name: Upgrade all packages
  command: pkg_add -u
  register: pkg_upgrade
  changed_when: pkg_upgrade.stdout | length > 0
  tags:
    - upgrade

- name: Clean package cache
  command: pkg_delete -a
  when: upgrade_clean_cache | bool
  changed_when: false
  failed_when: false
  tags:
    - upgrade
