---
galaxy_info:
  author: stepankutaj
  description: Prometheus node exporter for metrics collection
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - monitoring
    - prometheus
dependencies: []
