---



- name: Update prometheus-mysqld-exporter config
  template:
    src: prometheus-mysqld-exporter.j2
    dest: "/etc/default/prometheus-mysqld-exporter"
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus-mysqld-exporter


- name: Install prometheus-mysqld-exporter.
  package:
    name: "prometheus-mysqld-exporter"
    state: "present"


