---

### Nize uvedenou promenou nechavame zakomentovanou jelikoz chceme,
### aby byla pro kazdy server nastavena jina a zaroven, aby Ansible
### upozornil na nedefionovanou promenou.
###
### redis_password: Fc5w6446ER56g156GH5445s832iod

redis_databases: 16
redis_bind: 127.0.0.1
