---

### This variable is intentionally left undefined so that
### each server must set its own unique password and Ansible
### will alert on an undefined variable.
###
### redis_password: CHANGE_ME_USE_VAULT

redis_databases: 16
redis_bind: 127.0.0.1
