---
- name: Base infrastructure setup
  hosts: all,!pg
  become: true
  become_method: ansible.builtin.sudo
  become_user: root

  roles:
    - { role: motd, tags: motd }
    - { role: network, tags: network }
    - { role: ssh, tags: ssh }
    - { role: base, tags: base }
    - { role: sysusers, tags: sysusers }
    - { role: sudo, tags: sudo }
