---

# EXAMPLE:
# Required host vars:
#
# Minimal configuration:
# fail2ban_jails:
#   sshd: []
#
# Custom configuration:
# fail2ban_jails:
#   sshd:
#     - port = 29
#
# NOTE: CentOS uses jail name `sshd`, Ubuntu uses `ssh`
#
# TODO:
# Add condition to check if variable is an array in jail config, so empty arrays are not required in variables

fail2ban_ignoreip: "127.0.0.1/8"
fail2ban_bantime: 600
fail2ban_destemail: "root@{{inventory_hostname}}"
fail2ban_sender: "fail2ban@{{inventory_hostname}}"

